name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  DOMAIN:
    description: "Domain name""
    required: true
    default: "www.google.com"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
