name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: test action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          MY_NAME: "www.google.com"
