name: Workflow for testing ping action
on: push

jobs:
  build:
    name: test action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          DOMAIN: "www.google.com"
